### ISSUE TITLE
Pull from Duolingo plug-in

### ISSUE THREAD

**Issue by crsend** [JASchilz/AnkiSyncDuolingo#26] opened 2020-03-26 23:21 UTC
When I have been using the stand-alone Github application to create a Anki deck from Dueling I've had no issues.

But when using the plug in I receive this error message:
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.21 (f1734a47) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.3
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-03-26 15:54:30
Add-ons possibly involved: Pull from Duolingo

Caught exception:
Traceback (most recent call last):
  File "/Users/kennethfranciscus/Library/Application Support/Anki2/addons21/557761805/plugin.py", line 49, in sync_duolingo
    vocabulary_response = vocabulary_thread.join()
  File "/Users/kennethfranciscus/Library/Application Support/Anki2/addons21/557761805/duolingo_thread.py", line 29, in join
    raise e
  File "/Users/kennethfranciscus/Library/Application Support/Anki2/addons21/557761805/duolingo_thread.py", line 16, in run
    self.return_value.put(self._target(*self._args, **self._kwargs))
  File "/Users/kennethfranciscus/Library/Application Support/Anki2/addons21/557761805/duolingo.py", line 461, in get_vocabulary
    overview = overview_request.json()
  File "requests/models.py", line 897, in json
  File "json/__init__.py", line 357, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Please advise.

**Comment by JASchilz** [comment] 2020-03-27 04:11
Hi @crsend. I think that this is caused by the same problem as #25.

The issue is that there is some recent change to Duolingo that has made this plugin encounter an error.  I've reached out to the people who maintain the code library that I use to talk to Duolingo. 

To help keep people from getting confused, I've added a note to the plugin page that says that this plugin is temporarily broken.

I'm going to close this issue, not because it's fixed but because I think it has the same solution as issue #25 linked above. I encourage you to watch that issue and hopefully the team that maintains the other library can help us get a resolution soon.

**Closed as completed by JASchilz** 2020-03-27 04:11 UTC
