### ISSUE TITLE
Anki unresponsive after running plugin.

### ISSUE THREAD

**Issue by AndrewRRM** [JASchilz/AnkiSyncDuolingo#53] opened 2022-07-27 00:13 UTC
Macbook Air M1 (2020)
Big Sur 11.6.5

Pull from Duolingo not working for me.

Using Pull from Duolingo under tools, the sign in to duolingo is successful and it proceeds to “Add 3116 notes from German language?” When I click OK, Anki becomes unresponsive and I must eventually Force Quit (tried waiting for a loooong time ). No cards have been transferred. I have tried to restart Anki and restart computer to the same effect.

Would LOVE to be able to use this add on ...

**Comment by JASchilz** [comment] 2022-07-31 00:20
Hi Andrew! Let me take a look and get back to you within the next week.

I did recently update to the latest version of Anki and try running this
plugin. And although it *did* work for me, I did notice that it was fairly
slow and also that with the latest version of Anki the progress bar I
programmed in was broken. I'll try out a couple different things, like
using text updates instead of a progress bar, and I'll try downloading from
a language where I've got a ton of words like you do.

**Comment by AndrewRRM** [comment] 2022-07-31 00:25
Great! Thanks for the response/update.

**Comment by JASchilz** [comment] 2022-08-08 00:43
Hi Andrew! I found that:
  * Apparently the way that I was updating things like the progress bar during my pulls from Duolingo were kind of hacky.
  * Some recent changes to Anki caused my hacky code to fail.
  * Although I wasn't able to reproduce your issue specifically, I imagine that the kinds of problems my code was creating could result in different problems on different systems.
  * I rewrote this code.

This new code seems to be working well for me in the latest version of Anki. I'm going to clean it up over the next week or so before I officially publish it, but I _did_ make a "release candidate" that you can install manually if you have an opportunity:
  * Visit https://github.com/JASchilz/AnkiSyncDuolingo/releases/tag/1.2.1rc1
  * Download the duolingo_sync.ankiaddon file.
  * In Anki, use "Tools" -> "Add-ons" to:
    * **delete** your existing installation of this addon
    * "Install from file" the add-on file that you just downloaded
  * You'll then have to **restart** Anki before the change will take hold (the "Pull from Duoling" option will remain in the menu even before you restart, but it won't point to the new code till you restart).

If you do have an opportunity to use it, I'll of course be curious to know whether:
  * It works totally
  * Or if it doesn't work totally, you should hopefully now see a progress indicator that should advance 50 words at a time as it's pulling translations from Duolingo. If it always stops at around the same place or if it always stops at exactly the same place, then that would be an interesting clue.

Here's what that progress bar looks like for me, by the way: 
![image](https://user-images.githubusercontent.com/6137968/183318250-3ab8b933-34db-4947-b8b8-0b566f6c293c.png)

**Comment by AndrewRRM** [comment] 2022-08-08 01:49
Great work, thanks. Yep, imported more than 3000 words!

**Comment by JASchilz** [comment] 2022-08-08 03:14
Alright, glad to hear it! I'll close this issue after I clean up the code
and publish it for real.

**Comment by JASchilz** [comment] 2022-08-14 21:15
Hi Andrew! Based on our replies last week, it sounds like this issue is closed.

I have cleaned up the code and uploaded my latest build to Ankiweb. I'd be curious to hear if that version also works for you (you'd have to uninstall the current version of the plugin that you have installed, install the Ankiweb version, and restart Anki), but no need to try that out if you don't have a good opportunity.

Thanks again for raising this issue.

**Closed as completed by JASchilz** 2022-08-14 21:15 UTC

**Comment by AndrewRRM** [comment] 2022-08-14 23:17
OK, will do!
